CREATE DATABASE IF NOT EXISTS users DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'Password';
GRANT ALL PRIVILEGES ON users.* TO 'admin'@'localhost';
FLUSH PRIVILEGES;
USE users;
CREATE TABLE IF NOT EXISTS Users (id INT AUTO_INCREMENT PRIMARY KEY, userId VARCHAR(256), link VARCHAR(1024));
CREATE TABLE IF NOT EXISTS Schools (id INT AUTO_INCREMENT PRIMARY KEY, link VARCHAR(1024));