# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:   
  db:    
    image: mariadb:10.11.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Password
    volumes:
      - ./moodle-dump.sql:/docker-entrypoint-initdb.d/moodle-dump.sql
      - ./.data/db:/var/lib/mysql
    ports:
      - 3306:3306
  web:
    image: mesd-lms
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - 8080:80
    # use the links section if you want to use a container for a database.
    # if not, and you want to use an external database server, configure
    # if with the environment variables in the 'environment' section.
    # see README.md for more details.
    links:
      - db
    environment:
      - MOODLE_DB_HOST=db