version: "3.3"

services:
  server:
    build:
      context: RedirectAPI
      # target: final
      dockerfile: Dockerfile
    environment:
      - DB_Connection_String=server=redirectdb;port=3306;user=root;password=Password;database=users;
      - IAM_DOMAIN=https://gateway-cus-acc.gov.bw/
      - SHA_SECRET=secret
    ports:
      - 5000:80
  redirectdb:
    image: redirect-api-db
    build:
      context: RedirectAPI/DbServer
      dockerfile: Dockerfile
    expose:
      - 3306
  reportingdashboard:
    build:
      context: ReportingDashboard/server
      # target: final
      dockerfile: Dockerfile
    environment:
      - SERVER_DEV_PORT=3000
      - DB_DEV_USER=admin
      - DB_DEV_PASSWORD=Password
      # - DB_DEV_HOST=db
      - DB_DEV_PORT=3306
      - IAM_DEV_DOMAIN=https://gateway-cus-acc.gov.bw/
      - NUM_DBS=2
    ports:
      - 3000:3000
  web:
    image: mesd-lms
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8080:80"
    links:
      - db
    environment:
      - MOODLE_DB_HOST=db
      - MOODLE_DB_PORT=3306
      - SITE_PORT=8080
      - SITE_DOMAIN=http://13.49.225.7
  db:
    image: mariadb:10.11.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Password
    volumes:
      - ./moodle-dump.sql:/docker-entrypoint-initdb.d/moodle-dump.sql
      - ./.data/db:/var/lib/mysql
    ports:
      - "3306:3306"
  web1:
    image: mesd-lms
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "8081:80"
    links:
      - db1
    environment:
      - MOODLE_DB_HOST=db1
      - MOODLE_DB_PORT=3306
      - SITE_PORT=8081
      - SITE_DOMAIN=http://13.49.225.7
  db1:
    image: mariadb:10.11.7
    environment:
      - MYSQL_ROOT_PASSWORD=Password
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Password
    volumes:
      - ./moodle-dump.sql:/docker-entrypoint-initdb.d/moodle-dump.sql
      - ./.data/db-1:/var/lib/mysql
    ports:
      - "3307:3306"
