import { Component, OnInit } from '@angular/core';
import { ReportService } from '../../data-access/report.service';
import { ToastrService } from 'ngx-toastr';
import { BusyService } from 'src/app/shared/services/busy-service/busy.service';
import * as FileSaver from 'file-saver';
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

@Component({
  selector: 'app-profiling',
  templateUrl: './profiling.component.html',
  styleUrls: ['./profiling.component.css']
})
export class ProfilingComponent implements OnInit {

  constructor(private reportService: ReportService, private toastService: ToastrService, private busyService: BusyService) { }
  users = [
    {
      "id": 1,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "guest",
      "password": "$6$rounds=10000$BCEeNwSQiycuGIhc$TkFgpgBYjwEJIe5mE5h9CB/0abA426n3NI3h5zGJq/syuJMhObKE/bj7QaTwMA.ECRVDYB5DxpBb61q2SynMe0",
      "idnumber": "",
      "firstname": "Guest user",
      "lastname": " ",
      "email": "root@localhost",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 0,
      "lastaccess": 0,
      "lastlogin": 0,
      "currentlogin": 0,
      "lastip": "",
      "secret": "",
      "picture": 0,
      "description": "This user is a special user that allows read-only access to some courses.",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 0,
      "timemodified": 1702549853,
      "trustbitmask": 0,
      "imagealt": null,
      "lastnamephonetic": null,
      "firstnamephonetic": null,
      "middlename": null,
      "alternatename": null,
      "moodlenetprofile": null
    },
    {
      "id": 2,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "admin",
      "password": "$6$rounds=10000$vjbar/rJYw8p2KDr$RS59.lFDEnyd.sdH9L1UroiXmP9ZHLosEosoZ0I8En.Ev5n9wVtgR.g0P96S7BFwVZ0b7D773NTqax7IRU9s21",
      "idnumber": "",
      "firstname": "Abel",
      "lastname": "Tshimbalanga",
      "email": "pixelprocompanyco@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "Thamaga",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702550100,
      "lastaccess": 1706313602,
      "lastlogin": 1706083560,
      "currentlogin": 1706088882,
      "lastip": "0.0.0.0",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 1,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 0,
      "timemodified": 1705477317,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "599961600",
      "classname": "",
      "userrole": "Administrator",
      "contact": "",
      "nin": "1234567890",
      "phonenumber": "76199359",
      "onegovid": "nin1234567890",
      "level": "Standard 1"
    },
    {
      "id": 3,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "student1",
      "password": "$6$rounds=10000$rxrvrEDVgljHBZKp$Xb4J5QqnyoFQ5XkLb0DS7k8ikLaUKlPOxRxvMTB5Hsd.e0Q9.KdgA3wngk5RmPJup77TSK9Kpsr8P6D9B2EdR/",
      "idnumber": "",
      "firstname": "Student",
      "lastname": "Student",
      "email": "student@example.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702979841,
      "lastaccess": 1705325910,
      "lastlogin": 1705319850,
      "currentlogin": 1705325910,
      "lastip": "168.167.247.7",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1702979789,
      "timemodified": 1705141366,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "http://ec2-13-60-15-196.eu-north-1.compute.amazonaws.com/message/index.php?id=9",
      "gender": "Male",
      "dateofbirth": "1085094000",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Learner"
    },
    {
      "id": 4,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "teacher",
      "password": "$6$rounds=10000$8Bf3tBxcHgqafS/R$G5idlA3wlzYgWd9p1KKoMKKX0hOGUCXSKWwvAqwfkgAmsVpiWeplaIt2QteK8VO6HBsZ07Bmv9t61BMhlX.Bd1",
      "idnumber": "",
      "firstname": "Teacher",
      "lastname": "Teacher",
      "email": "teacher@example.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702980986,
      "lastaccess": 1704955937,
      "lastlogin": 1704955041,
      "currentlogin": 1704955863,
      "lastip": "41.223.192.1",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1702980653,
      "timemodified": 1704915816,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "695001600",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Educator"
    },
    {
      "id": 5,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "stud",
      "password": "$6$rounds=10000$60FQVRPXgCvF9ri3$qeHL1itd/HpnF33CsL0/M3R.sAd7VAT9GmCmIClgNMJmmEd6SfQAgkL/VRPCcvFzFn01EwBClv.7T0p304ese.",
      "idnumber": "",
      "firstname": "Stud",
      "lastname": "Stud",
      "email": "tamtonkhe@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702985100,
      "lastaccess": 1705338346,
      "lastlogin": 1705248047,
      "currentlogin": 1705335443,
      "lastip": "41.84.231.178",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1702981608,
      "timemodified": 1705335415,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Learner",
      "contact": "+268 78000000"
    },
    {
      "id": 6,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "student2",
      "password": "$6$rounds=10000$SAhf9kK/O9qM34t.$FFOGyR31onbeZ8muaMVZ6pSyFK5kjvmrScAEX0cokDwwvq6s02LdP6un9HeYjzmCj2W5wHYbmRr9fj4vRkX5j.",
      "idnumber": "",
      "firstname": "Student2",
      "lastname": "Student2",
      "email": "student2@example.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702984796,
      "lastaccess": 1705398866,
      "lastlogin": 1705325971,
      "currentlogin": 1705398866,
      "lastip": "41.223.73.227",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1702983514,
      "timemodified": 1705323313,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "1026774000",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Learner",
      "onegovid": ""
    },
    {
      "id": 7,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "student3",
      "password": "$6$rounds=10000$kK1wPK6ALV103tAG$Uf89CY9FABirDQsZfWrM7Znv3.evEeXGf1PRt1ujl3oOIFVROl9grtFKO5BmP49fYNNc8SiB9QJ4pIaYNfgMn.",
      "idnumber": "",
      "firstname": "Student3",
      "lastname": "Student3",
      "email": "student3@example.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702984766,
      "lastaccess": 1705399138,
      "lastlogin": 1702984766,
      "currentlogin": 1705399077,
      "lastip": "41.223.73.227",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1702983562,
      "timemodified": 1705399110,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Learner",
      "contact": "",
      "onegovid": ""
    },
    {
      "id": 8,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "student4",
      "password": "$6$rounds=10000$109vB2G0wpMoX/hT$cvWybnYrBsuCZKtrPDlukmnT1o2UfxlQsje7RvujHr4h6hmKnncNYM4yFQ0Ty5HSGZ5i2DTvFdYbm4WgVlnHE1",
      "idnumber": "",
      "firstname": "Student4",
      "lastname": "Student4",
      "email": "student4@example.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702984810,
      "lastaccess": 1705399218,
      "lastlogin": 1702984848,
      "currentlogin": 1705399154,
      "lastip": "41.223.73.227",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1702983601,
      "timemodified": 1705399190,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Learner",
      "contact": "",
      "onegovid": ""
    },
    {
      "id": 9,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "parent",
      "password": "$6$rounds=10000$02bn7dUGqeFyYwPo$QBZ3QitBBhURGR79I9/hy.KlXWGDsnXRaBAQ9RdRuxraeFrWXbNQTkYcva8RbjHEAqzP1m.UBY2vrzG2PCOAq0",
      "idnumber": "",
      "firstname": "Parent",
      "lastname": "Nkam",
      "email": "tamtonkhe5@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1702985297,
      "lastaccess": 1702985297,
      "lastlogin": 0,
      "currentlogin": 1702985297,
      "lastip": "41.215.153.227",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1702984513,
      "timemodified": 1705335322,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "contact": "",
      "Parent_Guardian": "",
      "gender": "",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Parent"
    },
    {
      "id": 10,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 1,
      "suspended": 0,
      "mnethostid": 1,
      "username": "atrocious@gmail.com.1703058416",
      "password": "$6$rounds=10000$TQ/bloJEPRezDMY0$TVrELqGCbOT5wA86AHtr54jYAZZGphZ6k6HGKXGUYh6Cu/g/buoBmB2FABNfVeA4Dni/MthUtAaS/nARRVnsr.",
      "idnumber": "",
      "firstname": "Yato",
      "lastname": "Noragmi",
      "email": "fa36d6185fe2b3840938aa8fedd04cdc",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1703021192,
      "lastaccess": 1703024219,
      "lastlogin": 1703022123,
      "currentlogin": 1703024219,
      "lastip": "41.223.192.1",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1703021142,
      "timemodified": 1703058416,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": ""
    },
    {
      "id": 11,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "hod",
      "password": "$6$rounds=10000$AHSwnaz/gixMyaJG$mOmEqLdpVbV2XmII1bNAhg7sTrW2SiS9Z2BPf8He3WlXe.VZzWKZoxrvAj3LreyTTSYPPgyw00qpEdgRU4nkj.",
      "idnumber": "",
      "firstname": "Head",
      "lastname": "O'Department",
      "email": "rulesrule@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1703062205,
      "lastaccess": 1705052356,
      "lastlogin": 1704443321,
      "currentlogin": 1705052283,
      "lastip": "102.134.169.52",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1703058623,
      "timemodified": 1705052352,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Head of Department"
    },
    {
      "id": 12,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "minadmin",
      "password": "$6$rounds=10000$RiwHkjyP9C3AUKZh$kjdjEoPi2KDEwNr5IMic9OgIb8LVwEy/34FNE6a9KX65939yWmEORXdh1wZv3Kc1ay4AwyfFjQRtOMCmQL6vX/",
      "idnumber": "",
      "firstname": "Mini",
      "lastname": "Mouse",
      "email": "disneyworld@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1704443080,
      "lastaccess": 1705053793,
      "lastlogin": 1705053308,
      "currentlogin": 1705053398,
      "lastip": "102.134.169.52",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1703224088,
      "timemodified": 1705053172,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Administrator"
    },
    {
      "id": 13,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "senior_ed",
      "password": "$6$rounds=10000$0A9C4XTA.Tr1JW2O$n3kT0rf/UUSNB9WjHUHlbKqfNfcgZ6clA1Vg1bpamntLbCBDxdNgUgZ4DWRby3nm0qwd3KJv79qFQyYvE6eK0/",
      "idnumber": "",
      "firstname": "Senior",
      "lastname": "Educator",
      "email": "senioreducator@example.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1703324719,
      "lastaccess": 1705259133,
      "lastlogin": 1705053815,
      "currentlogin": 1705259133,
      "lastip": "168.167.23.99",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1703324643,
      "timemodified": 1704916099,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Senior Educator"
    },
    {
      "id": 14,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 1,
      "suspended": 0,
      "mnethostid": 1,
      "username": "yewotheu123456789@gmail.com.1704440057",
      "password": "$6$rounds=10000$25EOPVqIndYKGWFc$T1aBBJFyzJyUD40PAGWHg8X.mkAVfZ5bGDnuprljMqi2DDOOEBfgKSZLm1Kehrulew99ErXlkJUiXEILM2/Ge0",
      "idnumber": "",
      "firstname": "Yewo",
      "lastname": "Theu",
      "email": "dd7bd2503b9019b45457550868cb3e3a",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "Mochudi",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 0,
      "lastaccess": 0,
      "lastlogin": 0,
      "currentlogin": 0,
      "lastip": "",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1704415533,
      "timemodified": 1704440057,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": ""
    },
    {
      "id": 15,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 1,
      "suspended": 0,
      "mnethostid": 1,
      "username": "yewotheu123456789@gmail.com.1704651453",
      "password": "$6$rounds=10000$hnc/nm7n8dZRbe6O$hSYJQkSjIVdWgBiHws25R3zP5WnkvK996ucIS3qWoN5yuGRhbP8wv.rAdLHT/1emMXkwkWqGeJBkDVx4PZHJR.",
      "idnumber": "",
      "firstname": "Yewo",
      "lastname": "Theu",
      "email": "dd7bd2503b9019b45457550868cb3e3a",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "School name",
      "department": "IT",
      "address": "",
      "city": "Mochudi",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1704440854,
      "lastaccess": 1704650714,
      "lastlogin": 1704442360,
      "currentlogin": 1704650639,
      "lastip": "102.134.169.52",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1704440521,
      "timemodified": 1704651453,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": ""
    },
    {
      "id": 16,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "yewo",
      "password": "$6$rounds=10000$xfvPnKrz9Vjgr9i7$qOhmRwln5x/GWJ7AK9s3sZAUWn7UFB8CRQECqlIfjvHcEM.FzGV4J/wHAFLwbf0.dXFVacSm44er0hG16oz9s0",
      "idnumber": "184118920",
      "firstname": "Yewo",
      "lastname": "Theu",
      "email": "yewotheu123456789@gmail.com",
      "emailstop": 0,
      "phone1": "76199359",
      "phone2": "76199359",
      "institution": "University of Botswana",
      "department": "Business",
      "address": "Mochudi, Botswana",
      "city": "Mochudi",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1704651861,
      "lastaccess": 1705051683,
      "lastlogin": 1704955851,
      "currentlogin": 1705051683,
      "lastip": "102.134.169.52",
      "secret": "",
      "picture": 5201,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1704651659,
      "timemodified": 1704651659,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "Theu",
      "firstnamephonetic": "Yewo",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "965343600",
      "classname": "",
      "level": "Level 400",
      "userrole": "Learner"
    },
    {
      "id": 17,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "teach",
      "password": "$6$rounds=10000$Ygh7.FaWLSB7OCO2$0xCid4WLy3YTqrzG0yvqketUoF7cEdTpObROscoXZRIg.rHUOHSyG5ePaDgeIZ1ZvhBzjXL.3COvAqDM7n.QM0",
      "idnumber": "",
      "firstname": "teacher",
      "lastname": "teacher",
      "email": "teacher@teacher.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1704813485,
      "lastaccess": 1705483138,
      "lastlogin": 1705417674,
      "currentlogin": 1705483138,
      "lastip": "168.167.53.233",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1704813337,
      "timemodified": 1704813511,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Educator"
    },
    {
      "id": 18,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "lecture",
      "password": "$6$rounds=10000$g3xspjbpb9FgJXtC$hMhCtc4Myxd5b5F7Y.pteoZjgXdQX.GxXnimzBwZi.li5qbKEgCgyV1kxLHh7VzmrAF4XSzoHe31JLnY5HihM0",
      "idnumber": "",
      "firstname": "Teach",
      "lastname": "Nkam",
      "email": "teachnkam@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1704881392,
      "lastaccess": 1704881392,
      "lastlogin": 0,
      "currentlogin": 1704881392,
      "lastip": "41.84.224.40",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1704881264,
      "timemodified": 1704881412,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Educator"
    },
    {
      "id": 19,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "bernardsebakile",
      "password": "$6$rounds=5000$oFfUdi4FowxEqJqQ$y7SXFfmNSMM4Wrf6.L0m1tkI/xtf3sB5TMtby1cbnVEYy1cVSR684riSgdgNaTWHkogcIB6T/j7LPBB4FeS9W.",
      "idnumber": "",
      "firstname": "Student",
      "lastname": "One",
      "email": "bksebakile@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 0,
      "lastaccess": 0,
      "lastlogin": 0,
      "currentlogin": 0,
      "lastip": "",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1704906485,
      "timemodified": 1704906485,
      "trustbitmask": 0,
      "imagealt": null,
      "lastnamephonetic": null,
      "firstnamephonetic": null,
      "middlename": null,
      "alternatename": null,
      "moodlenetprofile": null,
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "-2211753600",
      "classname": "A",
      "level": "Standard 1",
      "userrole": "Learner"
    },
    {
      "id": 20,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "webuser",
      "password": "$6$rounds=10000$253m/03DhlJ0MEqH$Sx/eM7v8YvRIA78wdP2GEYRidmcXih9E7zgEa8Px0XSShJEIhTGFwgtV4gUEJNXwG00G9nQowPSmu1ASnn4qA/",
      "idnumber": "",
      "firstname": "Web",
      "lastname": "User",
      "email": "webuser@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 0,
      "lastaccess": 0,
      "lastlogin": 0,
      "currentlogin": 0,
      "lastip": "",
      "secret": "",
      "picture": 0,
      "description": "<p>Has a service of GetUsersByCourseID;</p>\r\n<p> </p>\r\n<p> </p>\r\n<p> </p>\r\n<p>a2340de7c3123082859353b93b6849ee</p>",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705160066,
      "timemodified": 1705160302,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "",
      "dateofbirth": "0",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Administrator"
    },
    {
      "id": 21,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "sen",
      "password": "$6$rounds=10000$Nk49UP35BS98UI3v$mu60wUFsT6msS/6ikvZ6zIPR8jgkbdsLR.eeagFk2fsuPqAUFXj2K6jMwc.zAAbMn7xgujcK.fA47KqYN9Yhq/",
      "idnumber": "",
      "firstname": "Senior",
      "lastname": "Educator",
      "email": "senioreducator@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705246635,
      "lastaccess": 1705247998,
      "lastlogin": 1705247063,
      "currentlogin": 1705247998,
      "lastip": "41.215.152.185",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705246606,
      "timemodified": 1705246606,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Senior Educator"
    },
    {
      "id": 22,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "head",
      "password": "$6$rounds=10000$yuGqScT4y1IDL4Fj$77O1D8NBuf2S7J9mRt9WnhoiuGTKTiDd5CRiXQOT/7UkDPbkAuEz0bL0.MZNDB3JlGIFr5rMxoS9Au4KzYLWw1",
      "idnumber": "",
      "firstname": "Head",
      "lastname": "Dude",
      "email": "dude@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705248516,
      "lastaccess": 1705248935,
      "lastlogin": 1705248649,
      "currentlogin": 1705248935,
      "lastip": "41.215.152.185",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705248489,
      "timemodified": 1705248489,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Head of Department"
    },
    {
      "id": 23,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "educator",
      "password": "$6$rounds=10000$laDmbreogWA8g8WI$CRo2RKzGPJueRGmp1MYZbY3Wt1u/f86H.Y7HXBsFYPTbHD2v3MIVsnkoSC9g2W.kMFvItztIsETMkeWMEg/iG/",
      "idnumber": "123456789",
      "firstname": "Yewo",
      "lastname": "Theu",
      "email": "edu@edu.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "Mochudi",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705261416,
      "lastaccess": 1705824701,
      "lastlogin": 1705478921,
      "currentlogin": 1705824701,
      "lastip": "102.134.169.52",
      "secret": "",
      "picture": 5347,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705259400,
      "timemodified": 1705478957,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Female",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Educator",
      "contact": "",
      "nin": "",
      "phonenumber": "76199359"
    },
    {
      "id": 24,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "general",
      "password": "$6$rounds=10000$.etkRZ5PEPK6vee5$g4lRu8fWzmo8qcxgY7wkBq3snHNoFe.eUsgsqNBkxrZRTQWOIXME/M61dgTjicjPhkfzgDPsvPUziFV/.zVEm1",
      "idnumber": "",
      "firstname": "General",
      "lastname": "Teacher",
      "email": "teach@example.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "Molepolole",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "Africa/Gaborone",
      "firstaccess": 1705312635,
      "lastaccess": 1706008666,
      "lastlogin": 1705399640,
      "currentlogin": 1706008666,
      "lastip": "41.223.72.33",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705312549,
      "timemodified": 1705312549,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "297817200",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Learner"
    },
    {
      "id": 25,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "schoolhead",
      "password": "$6$rounds=10000$FYswn/lq5DKGOUUr$YItbw3vNiuF6nm9sQeaeIl1iZMtNMXE4s93QJ8Qb/wGpvR8nYhWTGb82mvhNPT4TBw.xa4cYhdNrDusDm8W0u/",
      "idnumber": "",
      "firstname": "School",
      "lastname": "Head",
      "email": "example@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "Mochudi",
      "country": "BW",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705318355,
      "lastaccess": 1705582091,
      "lastlogin": 1705328317,
      "currentlogin": 1705582091,
      "lastip": "41.223.192.1",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705318260,
      "timemodified": 1705582125,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "Parent_Guardian": "",
      "gender": "Male",
      "dateofbirth": "-503452800",
      "onegovid": "",
      "classname": "",
      "level": "",
      "userrole": "School Head",
      "contact": "",
      "nin": "123456789",
      "phonenumber": "76199359"
    },
    {
      "id": 26,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "seniored",
      "password": "$6$rounds=10000$GWqBCGLpqQmvroyj$vo7RWoVrZAOZShKS4sE4JJeZC.K8yno.P6IFyjOrJzfQsZqg9bTmxLOUkzYR0l/NOJUtYqzA2xqKqF56.7aUK1",
      "idnumber": "",
      "firstname": "Senior",
      "lastname": "Educator",
      "email": "senioreducator@test.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705514455,
      "lastaccess": 1705516571,
      "lastlogin": 1705516428,
      "currentlogin": 1705516571,
      "lastip": "168.167.53.233",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705514358,
      "timemodified": 1705514358,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "contact": "",
      "Parent_Guardian": "",
      "nin": "245612456",
      "phonenumber": "7777777",
      "gender": "Male",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Senior Educator"
    },
    {
      "id": 27,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "learner",
      "password": "$6$rounds=10000$d/X3h7uje62W0HXo$nOdK2H9amQtXCWECkhNi3jOsyfMnNTREppxFmvTaUH7cPXF6mAvVpmPlSf1dnWxnVHpqviM9jB0CdYAaWSaus/",
      "idnumber": "",
      "firstname": "learn",
      "lastname": "ing",
      "email": "learning@test.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705516195,
      "lastaccess": 1705600573,
      "lastlogin": 1705516597,
      "currentlogin": 1705600512,
      "lastip": "168.167.53.233",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705515995,
      "timemodified": 1705515995,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "contact": "",
      "Parent_Guardian": "",
      "nin": "787817878",
      "phonenumber": "78787878",
      "gender": "Male",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "Standard 1",
      "userrole": "Learner"
    },
    {
      "id": 28,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "schead",
      "password": "$6$rounds=10000$al6RRDO49eZTEIeL$20VikidNhKa7NfFQyNgY7mOICi7GDdRQPlwVW.ucCqtvCf1cPKG9UFqFCnVglCMe4ShPEpIX583Zjuy4GIpVO/",
      "idnumber": "",
      "firstname": "School",
      "lastname": "Head",
      "email": "scead@gmail.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705582413,
      "lastaccess": 1705582413,
      "lastlogin": 0,
      "currentlogin": 1705582413,
      "lastip": "41.84.243.116",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705582374,
      "timemodified": 1705582435,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "contact": "",
      "Parent_Guardian": "",
      "nin": "000 000 000 000 111",
      "phonenumber": "+267 7800 0004",
      "gender": "Female",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "",
      "userrole": "School Head"
    },
    {
      "id": 29,
      "auth": "manual",
      "confirmed": 1,
      "policyagreed": 0,
      "deleted": 0,
      "suspended": 0,
      "mnethostid": 1,
      "username": "learn2",
      "password": "$6$rounds=10000$8usgw2fIuC5DnGqV$a3BOxRQGyxHNA.MyOhyMH0qae9KZD8m5eufgBqlUHzBdLZC.dN/rdtVO1b7IWdeOwElVLEgPaeM14CVcSBcx9/",
      "idnumber": "",
      "firstname": "learningStuff",
      "lastname": "likePotaoes",
      "email": "learningStuff@test.com",
      "emailstop": 0,
      "phone1": "",
      "phone2": "",
      "institution": "",
      "department": "",
      "address": "",
      "city": "",
      "country": "",
      "lang": "en",
      "calendartype": "gregorian",
      "theme": "",
      "timezone": "99",
      "firstaccess": 1705600933,
      "lastaccess": 1705601010,
      "lastlogin": 1705600933,
      "currentlogin": 1705601010,
      "lastip": "168.167.53.233",
      "secret": "",
      "picture": 0,
      "description": "",
      "descriptionformat": 1,
      "mailformat": 1,
      "maildigest": 0,
      "maildisplay": 2,
      "autosubscribe": 1,
      "trackforums": 0,
      "timecreated": 1705600914,
      "timemodified": 1705600914,
      "trustbitmask": 0,
      "imagealt": "",
      "lastnamephonetic": "",
      "firstnamephonetic": "",
      "middlename": "",
      "alternatename": "",
      "moodlenetprofile": "",
      "contact": "",
      "Parent_Guardian": "",
      "nin": "123456788",
      "phonenumber": "71111111",
      "gender": "Male",
      "dateofbirth": "0",
      "onegovid": "",
      "classname": "",
      "level": "",
      "userrole": "Learner"
    }
  ];

  cols: any[];

  exportColumns: any[];




  ngOnInit(): void {
    this.busyService.busy();
    this.reportService.getUsers().subscribe(
      (response) => {
        let x: any = response;
        this.users = x;
        this.busyService.idle();
      },
      (error) => {
        this.busyService.idle();
        this.toastService.error(
          'An error has occured please try again and report the issue if it persists.',
          'Error'
        );
      }
    );

    this.cols = [
      { field: 'nin', header: 'National Identity Number', customExportHeader: 'Product Code' },
      { field: 'userrole', header: 'User Role' },
      { field: 'firstname', header: 'First Name' },
      { field: 'lastname', header: 'Last Name' },];


    this.exportColumns = this.cols.map(col => ({ title: col.header, dataKey: col.field }));

  }

  convertUnixTimestampToString(unixTimestamp) {
    if (unixTimestamp == 0 || unixTimestamp == null) {
      return "";
    }
    // Multiply by 1000 to convert from seconds to milliseconds
    const date = new Date(unixTimestamp * 1000);

    // Format the date-time string
    let day = ("0" + date.getDate()).slice(-2);
    let month = ("0" + (date.getMonth() + 1)).slice(-2);
    let year = date.getFullYear();


    return `${day}/${month}/${year}`;
  }

  exportPdf() {
    // const doc = new jsPDF();
    const doc = new jsPDF('p', 'pt');
    doc['autoTable'](this.exportColumns, this.users);
    // doc.autoTable(this.exportColumns, this.products);
    doc.save("users.pdf");
  }

  exportExcel() {
    import("xlsx").then(xlsx => {
      const worksheet = xlsx.utils.json_to_sheet(this.users);
      const workbook = { Sheets: { 'data': worksheet }, SheetNames: ['data'] };
      const excelBuffer: any = xlsx.write(workbook, { bookType: 'xlsx', type: 'array' });
      this.saveAsExcelFile(excelBuffer, "products");
    });
  }
  saveAsExcelFile(buffer: any, fileName: string): void {
    let EXCEL_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8';
    let EXCEL_EXTENSION = '.xlsx';
    const data: Blob = new Blob([buffer], {
      type: EXCEL_TYPE
    });
    FileSaver.saveAs(data, fileName + '_export_' + new Date().getTime() + EXCEL_EXTENSION);
  }


}

