<?php
/*
@lomsRef: @theme_loms/layout
 */

defined('MOODLE_INTERNAL') || die();

$templatecontext = [
    'sitename'                  => format_string($SITE->shortname, true, ['context' => context_course::instance(SITEID), "escape" => false]),
    'output'                    => $OUTPUT,
    'pageheading'               => $pageheading,
    'leftblocks'                => $leftblocks,
    'user_profile_picture'      => new moodle_url('/user/pix.php/'.$USER->id.'/f1.jpg'),
    'profile_icon_username'     => $lomsProfileIconUsername,
    'login_url'                 => $login_url,
    'signup_url'                => $signup_url,
    'isloggedin'                => $isloggedin,
    'sidepreblocks'             => $blockshtml,
    'hasblocks'                 => $hasblocks,
    'bodyattributes'            => $bodyattributes,
    'primarymoremenu'           => $primarymenu['moremenu'],
    'secondarymoremenu'         => $secondarynavigation ?: false,
    'mobileprimarynav'          => $primarymenu['mobileprimarynav'],
    'usermenu'                  => $primarymenu['user'],
    'langmenu'                  => $primarymenu['lang'],
    'headercontent'             => $headercontent,
    'overflow'                  => $overflow,
    'addblockbutton'            => $addblockbutton,
    'blocks_fullwidth_top'      => $blocks_fullwidth_top,
    'blocks_fullwidth_bottom'   => $blocks_fullwidth_bottom,
    'blocks_above_content'      => $blocks_above_content,
    'has_blocks_above_content'  => !empty($blocks_above_content),
    'blocks_below_content'      => $blocks_below_content,
    'has_blocks_below_content'  => !empty($blocks_below_content),
    'has_blocks_fullwidth_top'  => !empty($blocks_fullwidth_top),
    'regionmainsettingsmenu'    => $regionmainsettingsmenu,
    'hasregionmainsettingsmenu' => !empty($regionmainsettingsmenu),
    'loms_globalsearch_navbar' => $loms_globalsearch_navbar,
    'logo_visibility'           => $logo_visibility,
    'main_logo'                 => $main_logo,
    'logo_styles'               => $logo_styles,
    'mobile_logo'               => $mobile_logo,
    'mobile_logo_styles'        => $mobile_logo_styles,
    'header_search_bar'         => $header_search,
    'top_header_content'        => $top_header_content,
    'top_header_right_content'  => $top_header_right_content,
    'top_header'                => $top_header,
    'header_btn_url'            => $header_btn_url,
    'header_left_btn_text'      => $header_left_btn_text,
    'header_left_btn_url'       => $header_left_btn_url,
    'header_btn_icon'           => $header_btn_icon,

    'footer_logo_visibility'    => $footer_logo_visibility,
    'main_footer_logo'          => $main_footer_logo,
    'footer_shape_img1'          => $footer_shape_img1,
    'footer_shape_img2'          => $footer_shape_img2,
    'footer_logo_styles'        => $footer_logo_styles,

    'social_target_href' => $social_target_href,
    'loms_facebook_url' => get_config('theme_loms', 'loms_facebook_url'),
    'loms_twitter_url' => get_config('theme_loms', 'loms_twitter_url'),
    'loms_instagram_url' => get_config('theme_loms', 'loms_instagram_url'),
    'loms_pinterest_url' => get_config('theme_loms', 'loms_pinterest_url'),
    'loms_dribbble_url' => get_config('theme_loms', 'loms_dribbble_url'),
    'loms_google_url' => get_config('theme_loms', 'loms_google_url'),
    'loms_youtube_url' => get_config('theme_loms', 'loms_youtube_url'),
    'loms_vk_url' => get_config('theme_loms', 'loms_vk_url'),
    'loms_500px_url' => get_config('theme_loms', 'loms_500px_url'),
    'loms_behance_url' => get_config('theme_loms', 'loms_behance_url'),
    'loms_digg_url' => get_config('theme_loms', 'loms_digg_url'),
    'loms_flickr_url' => get_config('theme_loms', 'loms_flickr_url'),
    'loms_foursquare_url' => get_config('theme_loms', 'loms_foursquare_url'),
    'loms_linkedin_url' => get_config('theme_loms', 'loms_linkedin_url'),
    'loms_medium_url' => get_config('theme_loms', 'loms_medium_url'),
    'loms_meetup_url' => get_config('theme_loms', 'loms_meetup_url'),
    'loms_snapchat_url' => get_config('theme_loms', 'loms_snapchat_url'),
    'loms_tumblr_url' => get_config('theme_loms', 'loms_tumblr_url'),
    'loms_vimeo_url' => get_config('theme_loms', 'loms_vimeo_url'),
    'loms_wechat_url' => get_config('theme_loms', 'loms_wechat_url'),
    'loms_whatsapp_url' => get_config('theme_loms', 'loms_whatsapp_url'),
    'loms_wordpress_url' => get_config('theme_loms', 'loms_wordpress_url'),
    'loms_weibo_url' => get_config('theme_loms', 'loms_weibo_url'),
    'loms_telegram_url' => get_config('theme_loms', 'loms_telegram_url'),
    'loms_moodle_url' => get_config('theme_loms', 'loms_moodle_url'),
    'loms_amazon_url' => get_config('theme_loms', 'loms_amazon_url'),
    'loms_slideshare_url' => get_config('theme_loms', 'loms_slideshare_url'),
    'loms_soundcloud_url' => get_config('theme_loms', 'loms_soundcloud_url'),
    'loms_leanpub_url' => get_config('theme_loms', 'loms_leanpub_url'),
    'loms_xing_url' => get_config('theme_loms', 'loms_xing_url'),
    'loms_bitcoin_url' => get_config('theme_loms', 'loms_bitcoin_url'),
    'loms_twitch_url' => get_config('theme_loms', 'loms_twitch_url'),
    'loms_github_url' => get_config('theme_loms', 'loms_github_url'),
    'loms_gitlab_url' => get_config('theme_loms', 'loms_gitlab_url'),
    'loms_forumbee_url' => get_config('theme_loms', 'loms_forumbee_url'),
    'loms_trello_url' => get_config('theme_loms', 'loms_trello_url'),
    'loms_weixin_url' => get_config('theme_loms', 'loms_weixin_url'),
    'loms_slack_url' => get_config('theme_loms', 'loms_slack_url'),

    'footer_copyright'       => $footer_copyright,
    'banner_bg_image'     => $banner_bg_image,
    'back_to_top'            => $back_to_top == 0,
    'hide_global_banner'     => $hide_global_banner == 0,
    'hide_guest_access_curriculum'            => $hide_guest_access_curriculum == 0,

    'favicon'                   => $favicon,
    'footer_column_1' => $footer_column_1,
    'footer_column_2' => $footer_column_2,
    'footer_column_3' => $footer_column_3,
    'footer_column_4' => $footer_column_4,
    'footer_column_5' => $footer_column_5,
    'footer_col_1_class' => $footer_col_1_class,
    'footer_col_2_class' => $footer_col_2_class,
    'footer_col_3_class' => $footer_col_3_class,
    'footer_col_4_class' => $footer_col_4_class,
    'footer_col_5_class' => $footer_col_5_class,
    'footer_col_1_title' => get_config('theme_loms', 'footer_col_1_title'),
    'footer_info' => get_config('theme_loms', 'footer_info'),
    'footer_col_1_body' => get_config('theme_loms', 'footer_col_1_body'),
    'footer_col_2_title' => get_config('theme_loms', 'footer_col_2_title'),
    'footer_col_2_body' => get_config('theme_loms', 'footer_col_2_body'),
    'footer_col_3_title' => get_config('theme_loms', 'footer_col_3_title'),
    'footer_col_3_body' => get_config('theme_loms', 'footer_col_3_body'),
    'footer_col_4_title' => get_config('theme_loms', 'footer_col_4_title'),
    'footer_col_4_body' => get_config('theme_loms', 'footer_col_4_body'),
    'footer_col_5_title' => get_config('theme_loms', 'footer_col_5_title'),
    'footer_col_5_body' => get_config('theme_loms', 'footer_col_5_body'),

];
$PAGE->requires->jquery();